on:
  push:
name: organize-images
jobs:
  replace-external-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6.x"
      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Run script
        run: python scripts/replace_external_links.py
        env:
          HACKMD_EMAIL: ${{ secrets.HACKMD_EMAIL }}
          HACKMD_PASSWORD: ${{ secrets.HACKMD_PASSWORD }}
      - name: Commit to git
        run: |
          git config --global user.name 'mathesar-bot'
          git config --global user.email '82667229+mathesar-bot@users.noreply.github.com'
          git add -A
          git diff-index --quiet --cached HEAD || git commit -m "Remove external links"
          git push
  organize-images:
    needs: [replace-external-links]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6.x"
      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Run script
        id: run-script
        continue-on-error: true
        run: |
          output=$(python scripts/organize_images.py)
          echo "::set-output name=error-message::$output"
      - name: Commit to git
        run: |
          git config --global user.name 'mathesar-bot'
          git config --global user.email '82667229+mathesar-bot@users.noreply.github.com'
          git add -A
          git diff-index --quiet --cached HEAD || git commit -m "Organize images"
          git push
      - name: Error Message
        if: steps.run-script.outcome != 'success'
        run: |
          output="${{ steps.run-script.outputs.error-message }}"
          echo "::error file=,line=,col=::$output"
          exit 1
