on:
  schedule:
    # Run everyday at 00:00 UTC
    - cron: '0 0 * * *'
  push:
name: linkinator
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: 'https://wiki.mathesar.org'
          skip: 'http://matrix.mathesar.org/, https://hackmd.io/*, https://github.com/centerofci/mathesar-wiki'
