on:
  schedule:
    # Run everyday at 01:00 UTC
    - cron: '0 1 * * *'
name: linkinator
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: eito-fis/linkinator-action@v1.5.5
        with:
          paths: 'https://wiki.mathesar.org'
          skip: 'http://matrix.mathesar.org/, https://github.com/centerofci/mathesar-wiki'
